增加了minicpm3的sft、pretrain、dpo的配置参数
yangjianxin1/Firefly pull request #302
Opened 2024-10-18 06:49 UTC by LDLINGLINGLING

2024-10-21 12:36 UTC, yangjianxin1 requested changes
非常感谢minicpm团队的pr，整体pr没问题，建议把template_name替换成“minicpm3”，这样与此前的“minicpm”对齐，有助于用户理解辨别。

2024-10-21 12:54 UTC, yangjianxin1 requested changes

2024-10-21 12:54 UTC, yangjianxin1 commented on train_args/sft/qlora/minicpm3-4b-sft-qlora.json
> +    "template_name": "cpm3",
修改为“minicpm3”

2024-10-21 12:54 UTC, yangjianxin1 commented on train_args/dpo/full/cpm3-4b-dpo-full.json
> +    "template_name": "cpm3",
修改为“minicpm3”

2024-10-22 12:22 UTC, LDLINGLINGLING commented on train_args/dpo/full/cpm3-4b-dpo-full.json
> +    "template_name": "cpm3",
已经修改

2024-10-24 02:14 UTC, merged

2024-10-27 11:18 UTC, LDLINGLINGLING commented
![image](https://github.com/user-attachments/assets/18ecad6b-04af-4ac0-b987-bca025cec194)
友情链接已经放到，社区。能否在about中也加上minicpm3，非常感谢。